### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by boshi116** [tracemouse/luci-app-coredns#1]
程序 CoreDNS-1.10.1 linux/amd64, go1.20.1, c9ac2c9-dirty

**Comment by tracemouse** [comment]
看日志里面显示了什么

**Comment by tracemouse** [comment]
另外，可以手工尝试是不是能够运行：

/usr/share/coredns/coredns -conf=/usr/share/coredns/Corefile_custom

**Comment by boshi116** [comment]
手工命令起作用 显示正在运行

**Comment by tracemouse** [comment]
从release下载最新版，卸载掉旧版本然后重新安装，点击运行之后切换到日志那个页面看一下日志，或者手工打开/tmp/coredns.log看一下。

**Comment by boshi116** [comment]
> 从release下载最新版，载掉旧版本然后重新安装，点击运行之后切换到日志那一页看下一篇日志，或者动手操作打开/tmp/coredns.log看一下。

今天发现直接安装ipk可以正常使用，拉取源码直接编译到openwrt反倒不能正常开启
